[package]
name = "aws_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-dynamodb = "0.8.0"
aws-config = "0.8.0"
tokio = { version = "1.17.0", features = ["full"] }
